# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / Fortran
nav:
- Home: index.md
- 'Development Environment':
  - 'Overview':  'dev-env/overview.md'
  - 'Windows':  'dev-env/os-windows.md'
  - 'Cygwin':  'dev-env/os-cygwin.md'
  - 'Linux':  'dev-env/os-linux.md'
  - 'Fortran Compiler (Lahey)':  'dev-env/compiler-lahey.md'
  - 'Fortran Compiler (gfortran)':  'dev-env/compiler-gfortran.md'
  - 'Eclipse':  'dev-env/eclipse.md'
  - 'Eclipse Photran':  'dev-env/eclipse-photran.md'
- 'Fortran Language':
  - 'Overview':  'fortran/overview.md'
  - 'Main Program':  'fortran/main-program.md'
  - 'Modules':  'fortran/modules.md'
  - 'Functions':  'fortran/functions.md'
  - 'Subroutines':  'fortran/subroutines.md'
  - 'Input':  'fortran/input.md'
  - 'Output':  'fortran/output.md'
  - 'Logging':  'fortran/logging.md'
  - 'Error Handling':  'fortran/error-handling.md'
  - 'Documenting Code':  'fortran/doc-code.md'
- 'Developer Tasks':
   - 'Version Control': 'dev/git.md'
   - 'Testing': 'dev/testing.md'
   - 'Documentation': 'dev/doc.md'
   - 'Compile and Run': 'dev/compile-run.md'
   - 'Build and Deploy': 'dev/build-deploy.md'
- 'Other Topics':
   - 'Libraries': 'dev/libraries.md'
   - 'Static & Dynamic Executable': 'dev/static-dynamic-exe.md'
   - '32/64-bit': 'dev/32-64-bit-exe.md'
- 'Examples':
   - 'Overview': 'examples/overview.md'
- 'Fortran Tools for Water Resources':
   - 'Overview': 'water-resources/overview.md'
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  'Copyright Open Water Foundation'
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme.
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# # - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-fortran
site_author:  'Open Water Foundation'
site_description:  'Open Water Foundation Learn Fortran'
# ------------------------------------------------
# Use Material theme:
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.png'
